异常处理

try catch    本方法体内将问题处理掉
throws   将问题抛出本方法     无论是否出现异常都要使用try catch  将异常捕获 
如果在main 方法 抛出异常 则通过JVM默认方法处理  输出异常语句 结束调用
最好不要在主方法抛出 一定要处理
使用多个catch 捕获时          捕获时应当先将范围小的异常抛出,大范围的放在后面    子类在前 父类在后;